authentication/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('login/', loginPage, name='login'),
    path('register/', registerPage, name='register'),
    path('logout/', logoutUser, name='logout'),
]

covid_predictor/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', include(('main.urls', 'main'), namespace="main")),
    path('account/', include(('authentication.urls', 'authentication'), namespace="account")),
    path('admin/', admin.site.urls),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('', home, name='home'),
    path('result/', result, name='result'),
    path('history/', history, name='history')
]

authentication/models.py
from django.db import models

# Create your models here.

main/models.py
from django.contrib.auth.models import User
from django.db import models


class Prediction(models.Model):

    COVID = 0
    NORMAL = 1
    PNEUMONIA = 2

    OPTIONS = (
        (COVID, "COVID"),
        (NORMAL, 'Normal'),
        (PNEUMONIA, 'Pneumonia'),
    )

    user = models.ForeignKey(User, null=True, on_delete=models.CASCADE)
    uploaded_image_url = models.URLField(null=True)
    processed_image_url = models.URLField(null=True)
    diagnosis = models.CharField(max_length=15, choices=OPTIONS)
    date_created = models.DateTimeField(auto_now_add=True)

authentication/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from .views import *


def loginPage(request):
    if request.method == 'POST':
        email_address = request.POST['email']
        password = request.POST['password']
        user = authenticate(username=email_address, password=password)
        if user:
            login(request, user)
            return redirect('main:home')
        else:
            print('Invalid credentials')
    return render(request, 'authentication/login.html')


def registerPage(request):
    if request.method == 'POST':
        first_name = request.POST['firstname']
        last_name = request.POST['lastname']
        email_address = request.POST['email']
        password = request.POST['password']
        print(password)
        if not User.objects.filter(username=email_address).exists():
            User.objects.create_user(username=email_address,
                                     first_name=first_name,
                                     last_name=last_name,
                                     password=password)
            return redirect('account:login')
        else:
            print('User already exists')
    return render(request, 'authentication/register.html')


def logoutUser(request):
    logout(request)
    return redirect('main:home')

main/views.py
from django.shortcuts import render
from django.views.decorators.http import require_http_methods
from .models import Prediction
from django.core.files.storage import FileSystemStorage
from django.conf import settings
from cnn_model import compute_result


@require_http_methods(["GET"])
def home(request):
    return render(request, 'main/homepage.html')


@require_http_methods(["POST"])
def result(request):
    upload_directory = settings.MEDIA_ROOT + str(request.user.id) + "/uploads/"
    result_directory = settings.MEDIA_ROOT + str(request.user.id) + "/results/"
    upload_file_url = None
    processed_file_url = None
    diagnosis = Prediction.NORMAL

    if request.FILES.get('image'):
        uploaded_image = request.FILES.get('image')
        fs = FileSystemStorage(location=upload_directory)  # defaults to MEDIA_ROOT
        file_name = fs.save(uploaded_image.name, uploaded_image)
        upload_file_url = '/images/' + str(request.user.id) + "/uploads/" + file_name

        diagnosis = compute_result.process_image(upload_directory, result_directory, file_name)
        processed_file_url = '/images/' + str(request.user.id) + "/results/" + file_name

    user = None
    if request.user.is_authenticated:
        user = request.user
    prediction = Prediction.objects.create(
        user=user,
        diagnosis=diagnosis,
        uploaded_image_url=upload_file_url,
        processed_image_url=processed_file_url,
    )
    context = {
        'prediction': prediction
    }
    return render(request, 'main/result.html', context)


@require_http_methods(['GET'])
def history(request):
    print(request.user)
    predictions = Prediction.objects.filter(user=request.user)
    print(predictions)
    context = {
        'predictions': predictions
    }
    return render(request, 'main/history.html', context)

authentication/templates/authentication/login.html
{% load static %}

<!DOCTYPE html>

<html>

<head>
    <title>Covid Predictor</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
</head>

<body>
<!-- Navbar-->
<header class="header">
    <nav class="navbar navbar-expand-lg navbar-light py-3">
        <div class="container">
            <!-- Navbar Brand -->
            <a href="#" class="navbar-brand">
                <p class="title_text">Medi Check <span class="title_subtitle_text">An X-Ray Based Covid Predictor.</span></p>
            </a>
        </div>
    </nav>
</header>


<div class="container">
    <div class="row py-5 mt-4 align-items-center">
        <!-- For Demo Purpose -->
        <div class="col-md-5 pr-lg-5 mb-5 mb-md-0">
            <div class="row align-items-center justify-content-center ">
            <img src="https://res.cloudinary.com/mhmd/image/upload/v1569543678/form_d9sh6m.svg" alt=""
                 class="img-fluid mb-3 d-none d-md-block">
            <h1>Log in to your account</h1>
            <p class="font-italic text-muted mb-0">A machine learning based predictor</p>
            </div>
        </div>

        <!-- Registration Form -->
        <div class="col-md-7 col-lg-6 ml-auto">
            <form action="{% url 'account:login' %}" method="POST">
                {% csrf_token %}
                <div class="row">

                    <!-- Email Address -->
                    <div class="input-group col-lg-12 mb-4">
                        <div class="input-group-prepend">
                                <span class="input-group-text bg-white px-4 border-md border-right-0">
                                    <i class="fa fa-envelope text-muted"></i>
                                </span>
                        </div>
                        <input id="email" type="email" name="email" placeholder="Email Address"
                               class="form-control bg-white border-left-0 border-md" required autocomplete="false">
                    </div>

                    <!-- Password -->
                    <div class="input-group col-lg-12 mb-4">
                        <div class="input-group-prepend">
                                <span class="input-group-text bg-white px-4 border-md border-right-0">
                                    <i class="fa fa-lock text-muted"></i>
                                </span>
                        </div>
                        <input id="password" type="password" name="password" placeholder="Password"
                               class="form-control bg-white border-left-0 border-md" required autocomplete="false">
                    </div>

                    <!-- Submit Button -->
                    <div class="form-group col-lg-12 mx-auto mb-0">
                        <button type="submit" class="btn btn-primary btn-block py-2">
                            <span class="font-weight-bold">Log In</span>
                        </button>
                    </div>

                    <!-- Divider Text -->
                    <div class="form-group col-lg-12 mx-auto d-flex align-items-center my-4">
                        <div class="border-bottom w-100 ml-5"></div>
                        <span class="px-2 small text-muted font-weight-bold text-muted">OR</span>
                        <div class="border-bottom w-100 mr-5"></div>
                    </div>

                    <!-- New registration -->
                    <div class="text-center w-100">
                        <p class="text-muted font-weight-bold">New User? <a href="{% url 'account:register' %}"
                                                                            class="text-primary ml-2">Register</a>
                        </p>
                    </div>

                </div>
            </form>
        </div>
    </div>
</div>
</body>

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>

</html>

authentication/templates/authentication/register.html
{% load static %}

<!DOCTYPE html>

<html>

<head>
    <title>Covid Predictor</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
</head>

<body>
<!-- Navbar-->
<header class="header">
    <nav class="navbar navbar-expand-lg navbar-light py-3">
        <div class="container">
            <!-- Navbar Brand -->
            <a href="#" class="navbar-brand ">
                <p class="title_text">Medi Check <span class="title_subtitle_text">An X-Ray Based Covid Predictor.</span></p>
            </a>
        </div>
    </nav>
</header>


<div class="container">
    <div class="row py-5 mt-4 align-items-center">
        <!-- For Demo Purpose -->
        <div class="col-md-5 pr-lg-5 mb-5 mb-md-0">
            <div class="row align-items-center justify-content-center ">
            <img src="https://res.cloudinary.com/mhmd/image/upload/v1569543678/form_d9sh6m.svg" alt=""
                 class="img-fluid mb-3 d-none d-md-block">
            <h1>Create an Account</h1>
            <p class="font-italic text-muted mb-0">A machine learning based predictor</p>
            </div>
        </div>

        <!-- Registration Form -->
        <div class="col-md-7 col-lg-6 ml-auto">
            <form action="{% url 'account:register' %}" method="POST">
                {% csrf_token %}
                <div class="row">

                    <!-- First Name -->
                    <div class="input-group col-lg-6 mb-4">
                        <div class="input-group-prepend">
                                <span class="input-group-text bg-white px-4 border-md border-right-0">
                                    <i class="fa fa-user text-muted"></i>
                                </span>
                        </div>
                        <input id="firstName" type="text" name="firstname" placeholder="First Name"
                               class="form-control bg-white border-left-0 border-md" required autocomplete="false">
                    </div>

                    <!-- Last Name -->
                    <div class="input-group col-lg-6 mb-4">
                        <div class="input-group-prepend">
                                <span class="input-group-text bg-white px-4 border-md border-right-0">
                                    <i class="fa fa-user text-muted"></i>
                                </span>
                        </div>
                        <input id="lastName" type="text" name="lastname" placeholder="Last Name"
                               class="form-control bg-white border-left-0 border-md" autocomplete="false">
                    </div>

                    <!-- Email Address -->
                    <div class="input-group col-lg-12 mb-4">
                        <div class="input-group-prepend">
                                <span class="input-group-text bg-white px-4 border-md border-right-0">
                                    <i class="fa fa-envelope text-muted"></i>
                                </span>
                        </div>
                        <input id="email" type="email" name="email" placeholder="Email Address"
                               class="form-control bg-white border-left-0 border-md" autocomplete="false" required>
                    </div>

                    <!-- Password -->
                    <div class="input-group col-lg-12 mb-4">
                        <div class="input-group-prepend">
                                <span class="input-group-text bg-white px-4 border-md border-right-0">
                                    <i class="fa fa-lock text-muted"></i>
                                </span>
                        </div>
                        <input id="password" type="password" name="password" placeholder="Password"
                               class="form-control bg-white border-left-0 border-md" autocomplete="false" required>
                    </div>

                    <!-- Password Confirmation -->
                    <div class="input-group col-lg-12 mb-4">
                        <div class="input-group-prepend">
                                <span class="input-group-text bg-white px-4 border-md border-right-0">
                                    <i class="fa fa-lock text-muted"></i>
                                </span>
                        </div>
                        <input id="passwordConfirmation" type="password" name="passwordConfirmation"
                               placeholder="Confirm Password" class="form-control bg-white border-left-0 border-md"
                               autocomplete="false" required>
                    </div>

                    <!-- Submit Button -->
                    <div class="form-group col-lg-12 mx-auto mb-0">
                        <button type="submit" class="btn btn-primary btn-block py-2">
                            <span class="font-weight-bold">Create your account</span>
                        </button>
                    </div>

                    <!-- Divider Text -->
                    <div class="form-group col-lg-12 mx-auto d-flex align-items-center my-4">
                        <div class="border-bottom w-100 ml-5"></div>
                        <span class="px-2 small text-muted font-weight-bold text-muted">OR</span>
                        <div class="border-bottom w-100 mr-5"></div>
                    </div>

                    <!-- Already Registered -->
                    <div class="text-center w-100">
                        <p class="text-muted font-weight-bold">Already Registered? <a href="{% url 'account:login' %}"
                                                                                      class="text-primary ml-2">Login</a>
                        </p>
                    </div>

                </div>
            </form>
        </div>
    </div>
</div>
</body>

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>

</html>

main/templates/main/base.html
{% load static %}

<!DOCTYPE html>

<html>

<head>
    <title>Covid Predictor</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
</head>

<body>
<div class="base-container">
    {% include 'main/navbar.html' %}
    <div class="container-fluid">
        {% block content %}

        {% endblock %}
    </div>
    {% include 'main/footer.html' %}
</div>

</body>

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>
<script type="text/javascript" src="{% static 'js/main.js' %}"></script>
</html>

main/templates/main/footer.html
{% load static %}

<!-- Footer -->
<footer class="page-footer pt-4">

    <!-- Copyright -->
    <div class="footer-copyright text-center py-3 text-white bg-dark">
        <div class="container">
            <div class="row">
                <div class="col-md-6">Copyright © {% now "Y" %} Manas Uniyal. All rights reserved.
                </div>
                <div class="col-md-6">
                    <a href="https://github.com/ManasUniyal/CovidPredictor" target="_blank" class="my-style-icon fa fa-github fa-2x" rel="noopener noreferrer"></a>
                </div>
            </div>
        </div>
    </div>
    <!-- Copyright -->

</footer>
<!-- Footer -->

main/templates/main/history.html
{% extends 'main/base.html' %}

{% load static %}

{% block content %}

    <div class=container">
        {% if predictions %}
            {% for prediction in predictions %}
                <div class="card shadow p-3 mt-4 bg-white rounded border-dark">
                    <div class="row no-gutters">
                        <div class="col-md-4">
                            <div class="row align-items-center justify-content-center"><p style="font-size:20px;">
                                UPLOADED X-RAY</p></div>
                            <div class="row align-items-center justify-content-center"><img
                                    class="card-img style-image img-responsive img-thumbnail"
                                    src="{{ prediction.uploaded_image_url }} "></div>

                        </div>
                        <div class="col-md-4 ">
                            <div class="row align-items-center justify-content-center"><p style="font-size:20px;">
                                RESULT</p></div>
                            <div class="row align-items-center justify-content-center"><img
                                    class="card-img style-image img-responsive img-thumbnail"
                                    src="{{ prediction.processed_image_url }}"></div>
                        </div>
                        <div class="col-md-4 align-items-center justify-content-center">
                            <div class="card-body " style="white-space: pre-wrap;">
                                <div class="row align-items-center justify-content-center">
                                    <h2>Diagnosis: </h2>
                                    {% if prediction.diagnosis == "COVID19" %}
                                        <h3 style="color: red">{{ prediction.get_diagnosis_display }}</h3>
                                    {% elif prediction.diagnosis == "PNEUMONIA" %}
                                        <h3 style="color: red">{{ prediction.get_diagnosis_display }}</h3>
                                    {% else %}
                                        <h3 style="color: green">{{ prediction.get_diagnosis_display }}</h3>
                                    {% endif %}
                                </div>
                                <div class="row align-items-center justify-content-center">
                                    <h2>Date: </h2> {{ prediction.date_created }}</div>
                            </div>

                        </div>
                    </div>
                </div>
            {% endfor %}
        {% else %}
            <div class="col-md-12">
                <h1 class="row  align-items-center justify-content-center" style="height: 80vh;">No history to
                    display</h1>
            </div>
        {% endif %}
    </div>



{% endblock %}

main/templates/main/homepage.html
{% extends 'main/base.html' %}

{% load static %}

{% block content %}

    <div class="mt-4 mb-4 d-flex align-items-center">
        <div class="container">
            <div class="card text-center shadow-lg rounded border-dark">
                <div class="card-header">
                    <span style="font-weight: 700; font-size: 20px;">Upload X-Ray image for prediction</span>
                </div>
                <div class="row">
                    <div class="col-md-6">
                        <img class="m-3 card-img-top container justify-content-center img-responsive img-thumbnail"
                             id="image"
                             src="{% static 'images/default_image.gif' %}" alt="Card image cap">
                    </div>
                    <div class="col-md-6 upload-block">
                        <div class="card-body">
                            <form id="submit_image_form" method="POST" action="{% url 'main:result' %}"
                                  enctype="multipart/form-data">
                                {% csrf_token %}
                                <div class="row">
                                    <label class="btn btn-success btn-lg col-md-12">
                                        Upload X-Ray  <input id="img_upload" type="file" name="image" accept="image/*"
                                                           hidden>
                                    </label>
                                </div>
                            </form>
                            <div class="row predict_btn_prop" >
                                <button id="predict_btn" class="btn btn-primary btn-lg col-12 hide">Predict</button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    {% include 'main/modal.html' %}

{% endblock %}

main/templates/main/modal.html
<div class="modal" tabindex="-1" id="my-modal">
        <div class="modal-dialog modal-lg">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">History</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <p>You must be logged in to view previous predictions.</p>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary btn-danger btn-lg" data-dismiss="modal">Close</button>
                    <a href="{% url 'account:login' %}" class="btn btn-primary btn-lg">Log In</a>
                </div>
            </div>
        </div>
    </div>

main/templates/main/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="{% url 'main:home' %}"><p class="title_text">Medi Check <span class="title_subtitle_text">An X-Ray Based Covid Predictor</span>
    </p>
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
            aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'main:home' %}">Home <span class="sr-only">(current)</span></a>
            </li>
            {% if not user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'account:login' %}">Log In</a>
                </li>
            {% endif %}
            <li class="nav-item">
                {% if user.is_authenticated %}
                    <a class="nav-link" href="{% url 'main:history' %}">History</a>
                {% else %}
                    <a class="nav-link" data-toggle="modal" data-target="#my-modal" href="{% url 'main:history' %}">History</a>
                {% endif %}
            </li>
            {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'account:logout' %}">Log Out</a>
                </li>
            {% endif %}
        </ul>
    </div>
</nav>

main/templates/main/result.html
{% extends 'main/base.html' %}

{% load static %}

{% block content %}

    <div class="jumbotron d-flex align-items-center white-background">
        <div class="container">
            <div class="card text-center">
                <div class="card-header">
                    Prediction
                </div>
                <div class="row">
                    <div class="col-md-6">
                        <img class="m-3 card-img-top container justify-content-center img-responsive" id="image"
                             src="{{ prediction.processed_image_url }}" alt="Card image cap">
                    </div>
                    <div class="col-md-6 upload-block">
                        <div class="card-body ">
                            <div class="row align-items-center justify-content-center">
                                <h1 style="white-space: pre-wrap;">Diagnosis: </h1>
                                <h1 id="prediction-result"
                                    style="color: red; ">{{ prediction.get_diagnosis_display }} </h1>
                                <a class="btn btn-primary btn-block btn-lg" style="margin-top:20px ;"
                                   href="{% url 'main:home' %}">MAKE ANOTHER
                                    PREDICTION</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script>
        var user_name = document.getElementById("prediction-result");
        if (user_name.innerText === "NORMAL") user_name.style.color = "#00a651"
        else user_name.style.color = "#ff0000"
    </script>

    {% include 'main/modal.html' %}

{% endblock %}